# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=30)),
                ('score_increment', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('text', models.CharField(max_length=256)),
                ('node_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('twitter_name', models.CharField(max_length=30)),
                ('facebook_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=130)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
