# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171104_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textdump', models.TextField(null=True)),
            ],
        ),
    ]
