# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_postdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='associate_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
