# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_associate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendgridEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=150)),
                ('data', jsonfield.fields.JSONField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='associate_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='node_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
